### ISSUE TITLE
ログイン時のエラーの表示方法

### ISSUE THREAD

**Issue by okapiinosuke** [okapiinosuke/Backend_twitter_clone#2]
ログイン時に登録されていないアカウントや間違った入力に対するエラーを表示したいのですが、表示することができません。
原因は、LoginFormの定義方法あるのではないかと考えているのですが、いまいち何が悪いのかよくわかっていません。
何かまずい点があったら教えていただきたいです。よろしくお願いいたします。

**Comment by Akinori13** [comment]
`form = LoginForm(request.POST)`の書き方で正しいのか確認してください。BaseFormまで継承を遡り、コンストラクタの挙動を確認しましょう。
